#!/bin/sh

# Script Environment Variables
# -------------------------------------------------------------------------------------
# SYNOPKG_PKGNAME               =   Package identify which is defined in INFO
# SYNOPKG_PKGVER                =   Package version which is defined in INFO
# SYNOPKG_PKGDEST               =   Package destination path
#                                   /volume[x]/@appstore/[Package Name]
# SYNOPKG_TEMP_UPGRADE_FOLDER   =   Temporary upgrade folder
#                                   /volume1/@tmp/synopkg.tmp/[Package Name]
# -------------------------------------------------------------------------------------


# Important Paths, soft links and variables
# -------------------------------------------------------------------------------------
# DSM WebGUI folder
# /usr/syno/synoman/webman/3rdparty/[Package Name] -> /var/packages/[Package Name]/target
WEBGUI_FOLDER="/usr/syno/synoman/webman/3rdparty/${SYNOPKG_PKGNAME}"

# Soft link
# /var/packages/[Package Name]/target -> /volume1/@appstore/[Package Name]
PACKAGE_FOLDER="/var/packages/${SYNOPKG_PKGNAME}/target/ui"

# Timestamp - Formatting the Timestamp to terminate log entries
TIMESTAMP=$(date +%Y-%m-%d%t%H:%M:%S)
# -------------------------------------------------------------------------------------


# Action...
# -------------------------------------------------------------------------------------
# keep preinst robust even if language files are malformed
PKG_NOINSTALL_ERROR_PART1="The device"
PKG_NOINSTALL_ERROR_PART2="with CPU architecture"
PKG_NOINSTALL_ERROR_PART3="is not supported by synOCR because the required Docker package cannot be installed (x86_64 / aarch64)."
PKG_NOINSTALL_MISSING_DOCKER_ERROR="The Docker service is missing. Please install/start Container Manager before installing synOCR."

# prüft die Kompatibilität mit dem Paket Docker
machinetyp=$(uname --machine)
device=$( uname -a | awk -F_ '{print $NF}' | sed "s/+/plus/g" )

if [ $machinetyp != "x86_64" ] && [ $machinetyp != "aarch64" ]; then
    echo "${PKG_NOINSTALL_ERROR_PART1} (${device}) ${PKG_NOINSTALL_ERROR_PART2} ${machinetyp} ${PKG_NOINSTALL_ERROR_PART3}" > $SYNOPKG_TEMP_LOGFILE
    exit 1
fi

if [ ! -e "/var/run/docker.sock" ]; then
    echo "${PKG_NOINSTALL_MISSING_DOCKER_ERROR}" > $SYNOPKG_TEMP_LOGFILE
    exit 1
fi

exit 0
