#!/bin/sh

# Script Environment Variables
# -------------------------------------------------------------------------------------
# SYNOPKG_PKGNAME               =   Package identify which is defined in INFO
# SYNOPKG_PKGVER                =   Package version which is defined in INFO
# SYNOPKG_PKGDEST               =   Package destination path
#                                   /volume[x]/@appstore/[Package Name]
# SYNOPKG_TEMP_UPGRADE_FOLDER   =   Temporary upgrade folder
#                                   /volume1/@tmp/synopkg.tmp/[Package Name]
# -------------------------------------------------------------------------------------


# Important Paths, soft links and variables
# -------------------------------------------------------------------------------------
# DSM WebGUI folder
# /usr/syno/synoman/webman/3rdparty/[Package Name] -> /var/packages/[Package Name]/target
WEBGUI_FOLDER="/usr/syno/synoman/webman/3rdparty/${SYNOPKG_PKGNAME}"

# Soft link
# /var/packages/[Package Name]/target -> /volume1/@appstore/[Package Name]
PACKAGE_FOLDER="/var/packages/${SYNOPKG_PKGNAME}/target/ui"

# Timestamp - Formatting the Timestamp to terminate log entries
TIMESTAMP=$(date +%Y-%m-%d%t%H:%M:%S)

MYSCRIPT=$(basename "$0")
MYLOGIN=$(whoami)
MYID=$(id)
# -------------------------------------------------------------------------------------


# Action...
# -------------------------------------------------------------------------------------
case $1 in
    start)
        echo "Starting..."
        echo ''${TIMESTAMP}' - Start as '${MYID}'' >/tmp/${SYNOPKG_PKGNAME}.start
 #       [ -x /usr/local/bin/inotifywait ] || [ $(which inotifywait) ] && /bin/nohup /usr/syno/synoman/webman/3rdparty/synOCR/synOCR-start.sh start >/dev/null 2>&1 &
        [ $(which inotifywait) ] && /usr/syno/synoman/webman/3rdparty/synOCR/synOCR-start.sh start >/var/log/${SYNOPKG_PKGNAME}.log
        exit 0
      ;;
    stop)
        echo "Stopping..."
        echo ''${TIMESTAMP}' - Stop as '${MYID}'' >/tmp/${SYNOPKG_PKGNAME}.stop
  #      /usr/syno/synoman/webman/3rdparty/synOCR/synOCR-start.sh stop >/dev/null 2>&1 &
        /usr/syno/synoman/webman/3rdparty/synOCR/synOCR-start.sh stop >/var/log/${SYNOPKG_PKGNAME}.log
        exit 0
      ;;
    status)
        [ ! -t 1 ] || echo ''${TIMESTAMP}' - Running as '${MYLOGIN}' with '${MYID}'...'
        echo ''${TIMESTAMP}' - Running as '${MYLOGIN}' with '${MYID}'' >/tmp/${SYNOPKG_PKGNAME}.status
        exit 0
      ;;
    login)
        echo ''${TIMESTAMP}' - Running as '${MYLOGIN}' with '${MYID}'...'
        exit 0
      ;;
    *)
        echo ''${TIMESTAMP}' - Usage '${MYLOGIN}' start | stop | status | login'
        exit 1
      ;;
esac