#!/bin/sh

chroot /mnt/synoroot/ /usr/syno/synoman/webman/3rdparty/synOCR/check_permissions.sh

# resourcefile must be deleted to be able to delete the container without errors
rm -f /mnt/synoroot/var/packages/synOCR/conf/resource
